[package]
name = "atoi_radix10"
version = "0.2.0"
authors = ["Ivan Tham <pickfire@riseup.net>", "Giles Cope <gilescope@gmail.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "std" ]
std = []

[dependencies]
core_simd = { git="https://github.com/rust-lang/stdsimd.git"}
paste = "1.0"

[dev-dependencies]
criterion = {version="0.3", features=["html_reports"]}
itoa = "0.4"
criterion-cycles-per-byte = "0.1"

[[bench]]
name = "bench"
harness = false
