[package]
name = "parseint"
version = "0.1.0"
authors = ["Ivan Tham <pickfire@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0"
atoi = "0.4"
btoi = "0.4"
cluatoi = "0.2"

[dev-dependencies]
criterion = {version="0.3", features=["html_reports"]}
itoa = "0.4"

[[bench]]
name = "bench"
harness = false
